### ISSUE TITLE
Fragment

### ISSUE THREAD

**Issue by JWick90** [MatsuriDayo/nekoray#1191]
Hello
Can you please bring an update for Nekoray with the fragment ability ?
Thanks a lot.

**Comment by nimag02** [comment]
Hello Fragment feature is available now, just you need to change socks port in your custom config or fragment config to nekoray listening port.

**Comment by masonsafavi** [comment]
@nimag02 
Hello,
Would you please describe your solution?

**Comment by Ali-Flt** [comment]
@arm64v8a I know I have asked for this before but can you please add the option to change fragment settings in the UI (like many phone-based clients)? It will make our lives so much easier because it is much easier to send a copy paste-able vless link than sending a json config file and educating someone on how to import the json file as a custom xray config.

**Comment by Ali-Flt** [comment]
@masonsafavi I think the current solution is to create a new profile from server -> new profile and change the "Type" from "Socks" to Custom (Xray config). Then importing a complete json xray config (with fragment) into it.

**Comment by masonsafavi** [comment]
@Ali-Flt
Thanks for your attention, it works pretty good but can't get ping or traffic report with this method.
I'm currently using the following method without mentioned problems.
![fragment](https://github.com/MatsuriDayo/nekoray/assets/74149722/6923edb9-c42b-4d36-ad0a-6e329a01325c)
