### ISSUE TITLE
Torrent direct rule

### ISSUE THREAD

**Issue by papampi** [MatsuriDayo/nekoray#598]
Any helps on how to add torrent protocol direct rule?
Followed this https://guide.v2fly.org/routing/bittorrent.html#%E5%AE%A2%E6%88%B7%E7%AB%AF%E9%85%8D%E7%BD%AE
With no luck

**Comment by papampi** [comment]
Added this in Routing > Simple Route > Custom Route:
```
{
    "rules": [
        {
            "outboundTag": "direct",
            "protocol": [
                "bittorrent"
            ],
            "type": "field"
        }
    ]
}

```

But has no effect

**Comment by papampi** [comment]
Also tried in Routing > Custom Route (Global)

**Comment by papampi** [comment]
I'm using Neko on a workstation as default gateway for my home and deluge is installed on my  NAS.
I can install it in a docker and change its default gateway

Just wanted to know if its possible via custom routes or not.

**Comment by Probelp** [comment]
Had the same problem, tons of `connectex: No connection could be made because the target machine actively refused it.` errors in log on NekoBox 4.0-beta4.

Used TUN in whitelist mode, added `qbittorrent.exe` process name and `bittorrent` protocol to direct outbound. Nothing helps.

Problem solved by switching peer connection protocol from `utp and tcp` to `utp` only in `Options->Connection` in qbittorrent client. So how @arm64v8a clued: look in the bittorrent client's settings.
Anyway it is strange that the problem occurs while using TUN in whitelist mode and excluding the process name
