### ISSUE TITLE
Tun Mode Or System Proxy, Which should i Use? 

### ISSUE THREAD

**Issue by Jill117** [MatsuriDayo/nekoray#739]
Hello, i am using a v2ray server I've bought from someone, i added it to nekoray, at first when my core was xray, i couldn't use tun mode so i juse went with system proxy, but then i changed core and used tun mode, that worked well too, but which one should i use? Which one is safer for me and has higher security and data encryption?

**Comment by xchacha20-ietf-poly1305** [comment]
First, the security does not depends on wheather or not opening TUN.

Then, in normal situations, system mode's performance is better then TUN mode. But most of the time you can't feel it well.

Actually, I use TUN mode because it could help some applications which does not support proxy use proxy.

I hope these informations can help you.

**Comment by Jill117** [comment]
Thank you for answering ❤️, so i set it again to system proxy, I'm not really into these stuff so much so didn't know how they work, just searched about difference of proxy and vpn and got the answer that proxies don't encrypt data of user and etc, wanted to make sure it's safe using v2ray config bought from someone, thought they may be able to track my data and information, however i guess I'm just too just worried because i don't know how they work.

**Comment by xchacha20-ietf-poly1305** [comment]
The encryption is provided by your configurations instead of system proxy or TUN mode. So the security is same both proxy mode or TUN mode.
